https://stdana.atlassian.net/wiki/spaces/STDAN/pages/67141855/D1+assets

In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

# function: take one AID, read in csv, append AID, return df

def app_aid(stock):
    df = pd.read_csv(stock + '.csv')
    df['AID'] = stock
    return df

stocks = ['TEAM'
         ,'CRM'
         ,'BABA'
         ,'AMZN'
         ,'AAPL'
         ,'FB'
         ,'GOOGL'
         ,'MSFT'
         ,'AYX'
         ,'BRK-B'
         ,'SPY'
         ]

li = []

for stock in stocks:
    df = app_aid(stock)
    li.append(df)

# union
frame = pd.concat(li, axis=0, ignore_index=True)

# save csv
frame.to_csv('D1_assets.csv',index=False)

In [2]:
frame.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,AID
12693,2019-03-22,283.220001,283.799988,279.179993,279.250000,279.250000,122659300,SPY
12694,2019-03-25,278.869995,280.190002,277.640015,279.040009,279.040009,85575200,SPY
12695,2019-03-26,280.989990,282.179993,279.559998,281.119995,281.119995,68125900,SPY
12696,2019-03-27,281.109985,281.760010,277.929993,279.649994,279.649994,72224700,SPY
12697,2019-03-28,280.350006,281.209991,279.070007,280.709991,280.709991,56238500,SPY